services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: web-test-83n2-fe
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      PORT: 3000

