services:
  backend:
    extends:
      file: ./backend/docker-compose.yml
      service: app

  frontend:
    extends:
      file: ./frontend/docker-compose.yml
      service: web
    depends_on:
      backend:
        condition: service_started

networks:
  dbnetwork:
    external: true